### ISSUE TITLE
Reduce command - yq seems to ignore one of the yaml files in modules-filtered.txt

### ISSUE THREAD

**Issue by QualityRobD** [bjd2385/dynamic-continuation-orb#26]
## Orb version
latest. 
I'm running your orb's "code" locally as my environment cannot talk to outside orbs

## What happened
I'm calling your orb as such:
```yaml
workflows:
    version: 2
    setup:
        jobs:
            - orbsplicer/continue:
                context: $CONTEXT
                circleci-domain: $CI_DOMAIN
                circle-token: $CI_TOKEN
                github-organization: $CIRCLE_ORGANIZATION
                modules: |
                    /app
                    /technical_documentation
```

I made a change to a file in both `/app` and in `/technical_documentation`

/tmp/filtered-markdown.txt contains two lines:
```
.circleci/app.yml
.circleci/technical_documentation.yml
```

however the continue-config.yml only contains config from technical_documentation.yml, not both

## Expected behavior

.circleci/continue-config.yml to contain configurations for both configs

## Additional Information
I pulled your code locally and placed it in a private orb so I can leverage the awesome work you're doing here. I feel like I'm so close to getting everything working.
