### ISSUE TITLE
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by Joshua-Igoni** [bjd2385/dynamic-continuation-orb#60]
Hi I am having this error, when trying to trigger other pipelines based on file changes.

From the way i understand the Orb, it should trigger other pipelines in specific directories where there is a change.
But after configuring the orb, i notice it was actually filtering out the directories where the pipeline configs are targeting, but it isnt triggering the pipelines. rather it gives a git error.

Here is my config.yml below.

```
#/**************************************************************************
#******************    TOP LEVEL CONFIGURATION      ***********************#
#**************************************************************************/

version: 2.1

setup: true

orbs:
  dynamic: bjd2385/dynamic-continuation@3.6.7

workflows:
    test-workflow:
      jobs:
        - dynamic/continue:
            context: circleci
            root-config: config
            modules: |
              .
              web.frontend.src.main
```

this is the default config file located under .circleci dir
I have two other config files with the names test.yml and web.frontend.src.main.yml, they are also located in .circleci dir.

### Expected behavior
- when there are changes in root dir. test.yml executes
- when there are changes in web/frontend/src/main/ dir, web.frontend.src.main.yml executes

### Current behaviour
dynamic workflow executes(that is my config.yml)
auto detect detects the modules specified in confg, but pipeline is not executed despite the changes in those directories.

During the Filter step; this is the log of the error.

### ERROR

```
Auto-detected the following modules:

test
web.frontend.src.main

Collecting wildmatch==0.3.1
  Downloading wildmatch-0.3.1-py3-none-any.whl (4.1 kB)
Collecting pathspec==0.9.0
  Downloading pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
Installing collected packages: pathspec, wildmatch
Successfully installed pathspec-0.9.0 wildmatch-0.3.1

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
CircleCI received exit code 0

```

### additional information

My default branch is not master it is develop
