### ISSUE TITLE
when repo name contains number or '.' root pipeline is always ignored

### ISSUE THREAD

**Issue by Joshua-Igoni** [bjd2385/dynamic-continuation-orb#87]
I had two repos that i testing with this orb. one had a simple name "test-repo" the other had name like "test-repo-2.0" 

I set up basically two pipelines in each of them, the pipelines where very identical... for the first repo execution was fine, but for the second one with the number and "." the root pipeline was always ignored.

example pipeline configs to reproduce as follows:

app.yml(root-config pipeline)
```
 version: 2.1

executors:
   my_executorl:
    machine:
      image: ubuntu-2204:2022.04.2
      docker_layer_caching: true


#/**************************************************************************
#******************    JOBS CONFIGURATION AND SPECIFICATION   *************#
#**************************************************************************/


jobs:
  Unit_test:
    machine:
      image: ubuntu-2204:2022.04.2
      docker_layer_caching: true
    steps:
      - run:
          name: is this root?
          command: | 
            echo "this is root"

workflows:
  Base_tests:
    jobs:
      - Unit_test
```

the second pipeline that is listening for changes in a different directory
test.yml
```
version: 2.1

executors:
  my_executor:
    machine:
      image: ubuntu-2204:2022.04.2
      docker_layer_caching: true


#/**************************************************************************
#******************    JOBS CONFIGURATION AND SPECIFICATION   *************#
#**************************************************************************/


jobs:
  Unit_test:
    machine:
      image: ubuntu-2204:2022.04.2
      docker_layer_caching: true
    steps:
      - run:
          name: is it working
          command: | 
            echo "ok we are good"

workflows:
  Base_tests:
    jobs:
      - Unit_test
```

then the config for dynamic/continuation
config.yml
```
#/**************************************************************************
#******************    TOP LEVEL CONFIGURATION      ***********************#
#**************************************************************************/

version: 2.1

setup: true

orbs:
  dynamic: bjd2385/dynamic-continuation@3.6.7

workflows:
    test-workflow:
      jobs:
        - dynamic/continue:
            context: circleci-api
            default-branch: develop
            auto-detect: true
            root-config: app
            modules: |
              /
              /test
```

as explained earlier, this works fine for repos containing no number and '.' in their name, but ignores root config pipeline when the repo name has a number and/or . in the name
